core/urls.py
from django.conf.urls import include, url
from django.contrib.auth.views import login, logout
from . import views, forms

app_name = 'core'

urlpatterns = [
	## Participant
	url(r'^$', views.home, name='home'),
	url(r'^summary$', views.summary, name='summary'),
	url(r'^participant/$', views.participant_list, name='participant_list'),
	url(r'^participant/create/$', views.create_participant, name='create_participant'),
	url(r'^participant/edit/(?P<participant_id>[0-9]+)/$', views.edit_participant, name='edit_participant'),
	url(r'^participant/(?P<participant_id>[0-9]+)/$', views.forms, name='forms'),
	####

	## FADLI
	url(r'^participant/(?P<participant_id>[0-9]+)/form_a/$', views.form_a, name='form_a'),
	url(r'^participant/(?P<participant_id>[0-9]+)/form_a/', include('forms_a.urls')),
	url(r'^participant/(?P<participant_id>[0-9]+)/form_d/visit/(?P<visiting_id>[1-4])/$', views.form_d, name='form_d'),
	url(r'^participant/(?P<participant_id>[0-9]+)/form_d/visit/(?P<visiting_id>[1-4])/', include('forms_d.urls')),
	url(r'^participant/(?P<participant_id>[0-9]+)/form_d/visit/$', views.redirect_to_forms, name='form_d'),
	###


	## GAMA
	url(r'^participant/(?P<participant_id>[0-9]+)/form_b1/$', views.form_b1, name='form_b1'),
	url(r'^participant/(?P<participant_id>[0-9]+)/form_b1/', include('forms_b1.urls')),
	url(r'^participant/(?P<participant_id>[0-9]+)/form_b2/$', views.form_b2, name='form_b2'),
	url(r'^participant/(?P<participant_id>[0-9]+)/form_b2/', include('forms_b2.urls')),
	url(r'^participant/(?P<participant_id>[0-9]+)/form_b3/$', views.form_b3, name='form_b3'),
	url(r'^participant/(?P<participant_id>[0-9]+)/form_b3/', include('forms_b3.urls')),
	url(r'^participant/(?P<participant_id>[0-9]+)/form_c/$', views.form_c, name='form_c'),
	url(r'^participant/(?P<participant_id>[0-9]+)/form_c/', include('forms_c.urls')),
	####

	###LOGIN & LOGOUT
	url(r'^login/$', login, {'template_name': 'login.html', 'authentication_form': forms.LoginForm}, name='login'),
    url(r'^logout/$', logout, {'next_page': 'core:login'}, name='logout'),	
    ####
    #url(r'^[ -~]*$', views.home, name='anyurl'),
]

forms_c/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from . import views

app_name = 'forms_c'
urlpatterns = [
	url(r'^create$', views.create_form, name='create_form'),
	url(r'^(?P<form_id>[0-9]+)/check$', views.check_form, name='check_form'),
	url(r'^(?P<form_id>[0-9]+)/edit$', views.edit_form, name='edit_form'),
	url(r'^(?P<form_id>[0-9]+)/save$', views.save_form, name='save_form'),
	
	url(r'^(?P<form_id>[0-9]+)$', views.process_form, name='process_form'),

	url(r'^(?P<form_id>[0-9]+)/section1$', views.process_sectionC1, name='process_sectionC1'),
	url(r'^(?P<form_id>[0-9]+)/section2$', views.process_sectionC2, name='process_sectionC2'),
	url(r'^(?P<form_id>[0-9]+)/section3$', views.process_sectionC3, name='process_sectionC3'),
]

madament/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    ## CORE
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from __future__ import unicode_literals
from django.db import models

# Create your models here.
class Puskesmas(models.Model):
	puskesmas_id = models.CharField(max_length=5, blank=True)
	name = models.CharField(max_length=25, blank=True)
	def __str__(self):
		return "[puskesmas_id : " + unicode(self.puskesmas_id)+ ", name : "+unicode(self.name)+"]"
		
class Participant(models.Model):
	participant_id = models.CharField(max_length=10, blank=True)
	name = models.CharField(max_length=30, blank=True)
	date_admission = models.DateField()
	puskesmas = models.ForeignKey(Puskesmas, on_delete=models.PROTECT)
	created_by = models.CharField(max_length=25, blank=True)
	updated_by = models.CharField(max_length=25, blank=True)
	created_time = models.CharField(max_length=50, blank=True)
	updated_time = models.CharField(max_length=50, blank=True)
	active_status = models.BooleanField(default=True)
	def __str__(self):
		return "[participant_id : " + unicode(self.participant_id)+ ", name : "+unicode(self.name)+ ", active_status : "+unicode(self.active_status)+"]"

class Child(models.Model):
	child_id = models.CharField(max_length=12, blank=True)
	name = models.CharField(max_length=30, blank=True)
	mother = models.ForeignKey(Participant, on_delete=models.PROTECT)	
	def __str__(self):
		return "[mother name : " + unicode(self.mother.name)+ ", child name : "+unicode(self.name)+"]"

core/forms.py
from django.forms import *
from .models import * 
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.forms import AuthenticationForm 
from django.contrib.auth.models import User
import datetime

class LoginForm(AuthenticationForm):
    username = CharField(label="Username", max_length=30, 
                               widget=TextInput(attrs={'class': 'form-control', 'name': 'username', 'placeholder':'Username...'}))
    password = CharField(label="Password", max_length=30, 
                               widget=PasswordInput(attrs={'class': 'form-control', 'name': 'password', 'placeholder':'Password...'}))
    def __init__(self, *args, **kwargs):
        super(LoginForm,self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['autofocus'] = 'on'
        self.error_messages['invalid_login'] = "Your username and password didn't match. Please try again."

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email','first_name','last_name', 'password')     
        widgets = {'username' : TextInput(attrs={'autofocus' : '','class' : 'form-control form-username', 'id' :'form-username', 'placeholder' : 'Username...'}), 'email' : EmailInput(attrs={'class' : 'form-control'}), 'first_name' : TextInput(attrs={'class' : 'form-control'}), 'last_name' : TextInput(attrs={'class' : 'form-control'}),
                     'password' : PasswordInput(attrs={'class' : 'form-control form-password', 'id' :'form-password', 'placeholder' : 'Password...'})}
        help_texts = {
            'username': None,
        }
    def clean(self):
        username = self.cleaned_data.get("username")
        user = User.objects.get(username=username)
        password =  self.cleaned_data.get("password")
        if not user.check_password(password):
            msg = "Current Password wrong"
            self._errors["password"] = self.error_class([msg])
    def __init__(self, *args, **kwargs):
        super(UserForm,self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['readonly'] = True               

core/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import update_session_auth_hash
from .models import *
import datetime

## FORMS Fadli
from forms_a.models import *
from forms_d.models import *
##

## FORMS GAMA
from forms_b1.models import *
from forms_b2.models import *
from forms_b3.models import *
from forms_c.models import *
##

@login_required(login_url='core:login')
def home(request):
	return redirect('/participant')

@login_required(login_url='core:login')
def summary(request):
	if request.user.is_staff or True: ##kalau mau data entry biasa tidak bisa akses maka hapus or True nya
		#participants = Participant.objects.filter(active_status=True)
		participants = Participant.objects.all()
		summary_list = []
		number_of_completed_participant = 0

		###### filling summary_list ######
		for participant in participants:
			### form A ####
			try:
				form_a = ABaseLine.objects.get(participant=participant)
				if form_a.data_checked_id != None and form_a.data_checked_id != "":
					form_a_status = "3"
				elif form_a.is_save_all:
					form_a_status = "2"
				else:
					form_a_status = "1"
			except:
				form_a_status = ""
			####

			### form B1 ####
			try:
				form_b1 = B1Pregnancy.objects.get(participant=participant)
				if form_b1.data_checked_id != None and form_b1.data_checked_id != "":
					form_b1_status = "3"
				elif form_b1.is_save_all:
					form_b1_status = "2"
				else:
					form_b1_status = "1"	
			except:
				form_b1_status = ""
			####

			### form B2 ####
			try:
				form_b2 = B2Pregnancy.objects.get(participant=participant)
				if form_b2.data_checked_id != None and form_b2.data_checked_id != "":
					form_b2_status = "3"
				elif form_b2.is_save_all:
					form_b2_status = "2"
				else:
					form_b2_status = "1"	
			except:
				form_b2_status = ""
			####

			### form B3 ####
			try:
				form_b3 = B3Pregnancy.objects.get(participant=participant)
				if form_b3.data_checked_id != None and form_b3.data_checked_id != "":
					form_b3_status = "3"
				elif form_b3.is_save_all:
					form_b3_status = "2"
				else:
					form_b3_status = "1"	
			except:
				form_b3_status = ""
			####

			### form C ####
			form_c_all_complete = True
			try:
				form_c_list = CBirth.objects.filter(participant=participant)
				form_c_status = ""
				for form_c in form_c_list:
					if form_c.data_checked_id != None and form_c.data_checked_id != "":
						form_c_status = form_c_status + form_c.child_name + " - 3 | "
					elif form_c.is_save_all:
						form_c_status = form_c_status + form_c.child_name + " - 2 | "
						form_c_all_complete = False
					else:
						form_c_status = form_c_status + form_c.child_name + " - 1 | "
						form_c_all_complete = False	
				form_c_status = form_c_status[:-3]
			except:
				form_c_status = ""
				form_c_all_complete = False
			####

			### form D1 ####
			form_d1_all_complete = True
			try:
				form_d1_list = DInfant.objects.filter(participant=participant)
				form_d1_status = ""
				for form_d1 in form_d1_list:
					if form_d1.data_checked_id != None and form_d1.data_checked_id != "":
						form_d1_status = form_d1_status + form_d1.child_name + " - 3 | "
					elif form_d1.is_save_all:
						form_d1_status = form_d1_status + form_d1.child_name + " - 2 | "
						form_d1_all_complete = False
					else:
						form_d1_status = form_d1_status + form_d1.child_name + " - 1 | "
						form_d1_all_complete = False
				form_d1_status = form_d1_status[:-3]
			except:
				form_d1_status = ""
				form_d1_all_complete = False
			####

			### form D2 ####
			form_d2_all_complete = True
			try:
				form_d2_list = DInfant2.objects.filter(participant=participant)
				form_d2_status = ""
				for form_d2 in form_d2_list:
					if form_d2.data_checked_id != None and form_d2.data_checked_id != "":
						form_d2_status = form_d2_status + form_d2.child_name + " - 3 | "
					elif form_d2.is_save_all:
						form_d2_status = form_d2_status + form_d2.child_name + " - 2 | "
						form_d2_all_complete = False
					else:
						form_d2_status = form_d2_status + form_d2.child_name + " - 1 | "
						form_d2_all_complete = False	
				form_d2_status = form_d2_status[:-3]
			except:
				form_d2_status = ""
				form_d2_all_complete = False
			####

			### form D3 ####
			form_d3_all_complete = True
			try:
				form_d3_list = DInfant3.objects.filter(participant=participant)
				form_d3_status = ""
				for form_d3 in form_d3_list:
					if form_d3.data_checked_id != None and form_d3.data_checked_id != "":
						form_d3_status = form_d3_status + form_d3.child_name + " - 3 | "
					elif form_d3.is_save_all:
						form_d3_status = form_d3_status + form_d3.child_name + " - 2 | "
						form_d3_all_complete = False
					else:
						form_d3_status = form_d3_status + form_d3.child_name + " - 1 | "
						form_d3_all_complete = False
				form_d3_status = form_d3_status[:-3]
			except:
				form_d3_status = ""
				form_d3_all_complete = False
			####

			### form D4 ####
			form_d4_all_complete = True
			try:
				form_d4_list = DInfant4.objects.filter(participant=participant)
				form_d4_status = ""
				for form_d4 in form_d4_list:
					if form_d4.data_checked_id != None and form_d4.data_checked_id != "":
						form_d4_status = form_d4_status + form_d4.child_name + " - 3 | "
					elif form_d4.is_save_all:
						form_d4_status = form_d4_status + form_d4.child_name + " - 2 | "
						form_d4_all_complete = False
					else:
						form_d4_status = form_d4_status + form_d4.child_name + " - 1 | "
						form_d4_all_complete = False	
				form_d4_status = form_d4_status[:-3]
			except:
				form_d4_status = ""
				form_d4_all_complete = False
			####

			if form_a_status == "3" and form_b1_status == "3" and form_b2_status == "3" and form_c_all_complete and form_d1_all_complete and form_d2_all_complete and form_d3_all_complete and form_d4_all_complete:
				number_of_completed_participant = number_of_completed_participant + 1

			summary_list.append([participant.participant_id, participant.name, form_a_status, form_b1_status, form_b2_status, form_b3_status, form_c_status, form_d1_status, form_d2_status, form_d3_status, form_d4_status, participant.id, participant.active_status])	
		
		###### end of filling summary_list ######

		return render(request, 'core/summary.html', {'summary_list' : summary_list, 'number_of_completed_participant' : number_of_completed_participant})
	
	else:
		return home(request)


@login_required(login_url='core:login')
def create_participant(request):
	puskesmas_id = request.POST.get('puskesmas')
	number_of_people = Participant.objects.filter(puskesmas_id=puskesmas_id).count()
	puskesmas_obj = Puskesmas.objects.get(id=puskesmas_id)
	participant_obj = Participant()
	participant_obj.name = request.POST.get('participant_name')
	participant_obj.date_admission = request.POST.get('date_admission')
	participant_obj.participant_id =  puskesmas_obj.puskesmas_id+format_number(number_of_people+1)
	participant_obj.puskesmas_id = puskesmas_id
	participant_obj.created_by = request.user.username
	participant_obj.updated_by = request.user.username
	participant_obj.created_time = datetime.now()
	participant_obj.updated_time = datetime.now()
	participant_obj.save()
	return home(request)

### UNUSED SINCE EDIT PARTICIPANT IS NOT IMPLEMENTED 
@login_required(login_url='core:login')
def edit_participant(request, participant_id):
	participant_obj = Participant.objects.get(id=participant_id)
	participant_obj.name = request.POST.get('participant_name_edit')
	participant_obj.date_admission = request.POST.get('participant_date_edit')
	participant_obj.edited_by = request.user.username
	participant_obj.edited_time = datetime.now()
	participant_obj.save()
	return home(request)
###


def format_number(number):
	if number < 10:
		return "00" + str(number)
	elif number < 100:
		return "0" + str(number)
	else:
		return str(number)			

@login_required(login_url='core:login')
def redirect_to_forms(request, participant_id):
	return redirect('/participant/'+str(participant_id)+'/')	

@login_required(login_url='core:login')
def participant_list(request):
	participants = Participant.objects.filter(active_status=True)
	puskesmas_list = Puskesmas.objects.all()
	number_of_participants_list = []
	for puskesmas in puskesmas_list:
		number_of_participants_list.append(puskesmas.name + ": " + str(Participant.objects.filter(puskesmas=puskesmas).count()))	
	return render(request, 'core/home.html', {'number_of_participants_list' : number_of_participants_list,'participants' : participants, 'puskesmas_list' : puskesmas_list})


@login_required(login_url='core:login')
def forms(request, participant_id):
	participant = Participant.objects.get(id=participant_id)
	date_admission = participant.date_admission.__str__()
	return render(request, 'core/forms.html', {'participant' : participant, 'date_admission' : date_admission})

##################################
# form fadli
@login_required(login_url='core:login')
def form_a(request, participant_id):
	participant = Participant.objects.get(id=participant_id)
	forms = ABaseLine.objects.filter(participant_id=participant_id)
	date_admission = participant.date_admission.__str__()
	return render(request, 'core/form_a.html', {'participant' : participant, 'forms' : forms, 'date_admission' : date_admission})

@login_required(login_url='core:login')
def form_d(request, participant_id, visiting_id):
	participant = Participant.objects.get(id=participant_id)
	child_list = Child.objects.filter(mother=participant)
	forms = None
	visiting_number = ""
	if visiting_id == "1":
		forms = DInfant.objects.filter(participant_id=participant_id)
		visiting_number = "First"
	elif visiting_id == "2":
		forms = DInfant2.objects.filter(participant_id=participant_id)
		visiting_number = "Second"
	elif visiting_id == "3":
		forms = DInfant3.objects.filter(participant_id=participant_id)
		visiting_number = "Third"

core/templates/core/form_a.html
{% extends 'brief-header.html' %}
{% block content2 %}
 <!-- Page Content -->
 
        <!-- Form Umum Section -->
        <div class="mycenter">
        <div class="form-group row">
            {% if forms.count < 1 %}
            
            <h4 style="text-align: center; margin-top: 10px;"> List Form A ( Baseline Data) of  {{ participant.name }} </h4>

            <div class="col-md-4 col-md-offset-4" id="buttoncreateform">
                <a href="{{request.get_full_path}}create" class="btn btn-primary btn-lg btn-block">
                   <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Create Form A
                </a>
            </div>
            

            {% else %}
            
            <h4 style="text-align: center; margin-top: 10px;"> List Form A ( Baseline Data) of {{ participant.name }} </h4>
            
            {% endif %}
        </div>
        </div>

        <div class="list_all_form">
            <div class="form-group row">
                {% for form in forms %}
                    <div class="col-md-8 col-md-offset-2">
                        <a href="{{request.get_full_path}}{{form.id}}" class="btn btn-primary btn-lg btn-block">
                            {% if form.data_checked_id != None and form.data_checked_id != "" %}
                                Form A - {{ form.data_entry_id }}  - Checked
                            {% elif form.is_save_all %}
                                Form A - {{ form.data_entry_id }} - Submitted
                            {% else %}
                                Form A - {{ form.data_entry_id }} - On Progress    
                            {% endif %}
                        </a>
                    </div>
                {% endfor %}
            </div>            
        </div>

{% endblock %}

core/templates/core/form_b1.html
{% extends 'brief-header.html' %}
{% block content2 %}
 <!-- Page Content -->
 
        <!-- Form Umum Section -->    
    <div class="mycenter">
        <div class="form-group row">
            {% if forms.count < 1 %}
            
            <h4 style="text-align: center; margin-top: 10px;"> List Form B ( Pregnancy Trimester I ) of {{ participant.name }} </h4>

            <div class="col-md-4 col-md-offset-4">
                <a href="{{request.get_full_path}}create" class="btn btn-primary btn-lg btn-block">
                    <i class="fa fa-pencil-square-o" aria-hidden="true"></i>Create Form B1
                </a>
            </div>

            {% else %}
            
            <h4 style="text-align: center; margin-top: 10px;"> List Form B ( Pregnancy Trimester I ) of {{ participant.name }} </h4>
            
            {% endif %}
        </div>
    </div>

        <div class="list_all_form">
            
                {% for form in forms %}
                <div class="form-group row">
                    <div class="col-md-8 col-md-offset-2">
                        <a href="{{request.get_full_path}}{{form.id}}" class="btn btn-primary btn-lg btn-block">
                            {% if form.data_checked_id != None and form.data_checked_id != "" %}
                                Form B Trimester I - {{ form.data_entry_id }}  - Checked
                            {% elif form.is_save_all %}
                                Form B Trimester I - {{ form.data_entry_id }} - Submitted
                            {% else %}
                                Form B Trimester I - {{ form.data_entry_id }} - On Progress    
                            {% endif %}
                        </a>
                    </div>
                </div>
                {% endfor %}
                        
        </div>      

{% endblock %}

core/templates/core/form_b2.html
{% extends 'brief-header.html' %}
{% block content2 %}
 <!-- Page Content -->
 
        <!-- Form Umum Section -->
    
    <div class="mycenter">
        <div class="form-group row">
            {% if forms.count < 1 %}
            
            <h4 style="text-align: center; margin-top: 10px;"> List Form B ( Pregnancy Trimester II ) of {{ participant.name }} </h4>

            <div class="col-md-4 col-md-offset-4">
                <a href="{{request.get_full_path}}create" class="btn btn-primary btn-lg btn-block">
                   <i class="fa fa-pencil-square-o" aria-hidden="true"></i>Create Form B2
                </a>
            </div>
            
            {% else %}
            
            <h4 style="text-align: center; margin-top: 10px;"> List Form B ( Pregnancy Trimester II ) of {{ participant.name }} </h4>
            
            {% endif %}
        </div>
    </div>

        <div class="list_all_form">
            
                {% for form in forms %}
                <div class="form-group row">
                    <div class="col-md-8 col-md-offset-2">
                        <a href="{{request.get_full_path}}{{form.id}}" class="btn btn-primary btn-lg btn-block">
                            {% if form.data_checked_id != None and form.data_checked_id != "" %}
                                Form B Trimester II - {{ form.data_entry_id }}  - Checked
                            {% elif form.is_save_all %}
                                Form B Trimester II - {{ form.data_entry_id }} - Submitted
                            {% else %}
                                Form B Trimester II - {{ form.data_entry_id }} - On Progress    
                            {% endif %}
                        </a>
                    </div>
                </div>
                {% endfor %}
                        
        </div>      

{% endblock %}

core/templates/core/forms_c.html
{% extends 'base.html' %}
{% block content %}
 <!-- Page Content -->
 <div class="container">
        <!-- Form Umum Section -->
        <div class="jumbotron">         
            <form class="patient-form-data">
                <div class="row">
                    <div class="col-md-6 col-md-offset-3 col-xs-6 col-sm-6 col-sm-offset-3">
                        <div class="form-group">
                            <label for="participant_id"> Participant ID</label>
                            <input class="form-control disabled" type="text" value={{participant.participant_id}} disabled>
                        </div>

                        <div class="form-group">
                            <label for="participant_name"> Participant Name </label>
                            <input class="form-control" type="text" value={{participant.name}} disabled>
                        </div>

                        <div class="form-group">
                            <label for="date_admission"> Date Admission </label>
                            <input class="form-control" type="text" value={{date_admission}} disabled>
                        </div>                        
                    </div>                     
                </div> 
            </form>
        </div>
        <form action="{% url 'forms_c:create_form' %}"  method="GET">
            {% csrf_token %}
            <input type="hidden" name="participant_id" value={{participant.id}}>
            <input type="submit" class="btn btn-primary" value="Create Form C"/>
        </form>    
        <h4> List Form C ( Baseline) of {{ participant.name }} </h4>

        <div class="list_all_form">
            <div class="form-group row">
                {% for form in forms %}
                    <div class="col-md-8 col-md-offset-2">
                        <form action="{% url 'forms_c:process_sectionC1' %}"  method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="form_id" value={{form.id}}>
                            <input type="submit" class="btn btn-primary btn-lg btn-block" value="{{ form.id}} -- Form C - Birth"/>
                        </form>
                    </div>
                {% endfor %}
            </div>            
        </div>      
</div>
{% endblock %}

core/templates/core/home.html
{% extends 'base.html' %}
{% block content %}
<!-- Page Content -->
    <div class="container">
    <div>
        <div class="row">
            <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#createModal">
            <i class="fa fa-plus" aria-hidden="true"></i> Create Participant </button>
        </div>     

        <!-- Modal Create Participant --> 

         <div class="modal fade" id="createModal" tabindex="-1" role="dialog" aria-labelledby="createModallabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="createModal"><Create Participant</h4>
              </div>
              <form action="{% url 'core:create_participant' %}"  method="POST">
                  {% csrf_token %}
                  <div class="modal-body">
                        <div class="form-group">
                                <label for="participant_name"> Participant Name </label>
                                <input class="form-control " type="text" name="participant_name" id="participant_name" maxlength="30">
                        </div>
                        <div class="form-group">
                                <label for="puskesmas"> Puskesmas </label>
                                <!--<input class="form-control " type="text" name="puskesmas_code" id="puskesmas_code">-->

                                <select class="form-control selectpicker" name="puskesmas">                                 
                                  {% for puskesmas in puskesmas_list %}
                                  <option value={{puskesmas.id}}>{{ puskesmas.name }}</option>
                                  {% endfor %}
                                </select>
                        </div>
                        
                        <div class="form-group">
                                <label for="date_admission"> Date Admission </label>
                                <input class="form-control" type="date" id="date_admission" name="date_admission" required>
                        </div>
                                
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    <input type="submit" class="btn btn-primary" value="Create Participant"/>
                  </div>
                </form>
            </div>
          </div>
        </div> 
        <!-- End of Modal Create Participant-->

        <div class="row">         
           <h3> List of Participants </h3>
           <!-- <h4> Number of Registered Participant: {{ participants.count }} </h4>
           {% for item in number_of_participants_list %}
              <h4>{{ item }}</h4>
           {% endfor %} -->
            
          <!-- <table id="myTable" class="table table-striped table-bordered nowrap" cellspacing="0" width="100%"> -->

           <table id="myTable" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <!-- <th>Forms</th> -->
                        <th>Participant_ID</th>
                        <th>Name</th>
                        <th>Date Admission </th>
                        <th>Created by</th>
                    </tr>
                </thead>            
                <tbody>
                    {% load l10n %}
                    {% for participant in participants %}
                        <tr>
                            <!-- <td>
                              <a href="{{request.get_full_path}}{{participant.id}}" class="btn 
                              btn-primary">Forms</a>
                            </td> -->
                            <td>{{ participant.participant_id }}</td>
                            <td class='clickable-row' data-href="{{request.get_full_path}}{{participant.id}}">
                            {% if participant.name|length <= 25 %}
                              {{ participant.name }}
                            {% else %}
                              {{ participant.name|slice:"0:25" }}
                            {% endif %}

                            </td>
                            <td class='clickable-row' data-href="{{request.get_full_path}}{{participant.id}}">
                            {{ participant.date_admission|localize }}
                            </td>
                            <td class='clickable-row' data-href="{{request.get_full_path}}{{participant.id}}">{{ participant.created_by }}</td>
                            <!-- <td>
                              <a class="btn btn-info" data-toggle="modal" data-target="#editModal"> Edit Participant </a>
                            </td> -->
                        </tr>                      
                    {% endfor %}     
                </tbody>
           </table>
        </div>
      </div> 
    </div>
    <!-- /.container -->
{% endblock %}