core/urls.py
from django.conf.urls import include, url
from django.contrib.auth.views import login, logout
from . import views, forms

app_name = 'core'

urlpatterns = [
	## Participant
	url(r'^$', views.home, name='home'),
	url(r'^summary$', views.summary, name='summary'),
	url(r'^participant/$', views.participant_list, name='participant_list'),
	url(r'^participant/create/$', views.create_participant, name='create_participant'),
	url(r'^participant/edit/(?P<participant_id>[0-9]+)/$', views.edit_participant, name='edit_participant'),
	url(r'^participant/(?P<participant_id>[0-9]+)/$', views.forms, name='forms'),
	####

	## FADLI
	url(r'^participant/(?P<participant_id>[0-9]+)/form_a/$', views.form_a, name='form_a'),
	url(r'^participant/(?P<participant_id>[0-9]+)/form_a/', include('forms_a.urls')),
	url(r'^participant/(?P<participant_id>[0-9]+)/form_d/visit/(?P<visiting_id>[1-4])/$', views.form_d, name='form_d'),
	url(r'^participant/(?P<participant_id>[0-9]+)/form_d/visit/(?P<visiting_id>[1-4])/', include('forms_d.urls')),
	url(r'^participant/(?P<participant_id>[0-9]+)/form_d/visit/$', views.redirect_to_forms, name='form_d'),
	###


	## GAMA
	url(r'^participant/(?P<participant_id>[0-9]+)/form_b1/$', views.form_b1, name='form_b1'),
	url(r'^participant/(?P<participant_id>[0-9]+)/form_b1/', include('forms_b1.urls')),
	url(r'^participant/(?P<participant_id>[0-9]+)/form_b2/$', views.form_b2, name='form_b2'),
	url(r'^participant/(?P<participant_id>[0-9]+)/form_b2/', include('forms_b2.urls')),
	url(r'^participant/(?P<participant_id>[0-9]+)/form_b3/$', views.form_b3, name='form_b3'),
	url(r'^participant/(?P<participant_id>[0-9]+)/form_b3/', include('forms_b3.urls')),
	url(r'^participant/(?P<participant_id>[0-9]+)/form_c/$', views.form_c, name='form_c'),
	url(r'^participant/(?P<participant_id>[0-9]+)/form_c/', include('forms_c.urls')),
	####

	###LOGIN & LOGOUT
	url(r'^login/$', login, {'template_name': 'login.html', 'authentication_form': forms.LoginForm}, name='login'),
    url(r'^logout/$', logout, {'next_page': 'core:login'}, name='logout'),	
    ####
    #url(r'^[ -~]*$', views.home, name='anyurl'),
]

madament/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    ## CORE
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from __future__ import unicode_literals
from django.db import models

# Create your models here.
class Puskesmas(models.Model):
	puskesmas_id = models.CharField(max_length=5, blank=True)
	name = models.CharField(max_length=25, blank=True)
	def __str__(self):
		return "[puskesmas_id : " + unicode(self.puskesmas_id)+ ", name : "+unicode(self.name)+"]"
		
class Participant(models.Model):
	participant_id = models.CharField(max_length=10, blank=True)
	name = models.CharField(max_length=30, blank=True)
	date_admission = models.DateField()
	puskesmas = models.ForeignKey(Puskesmas, on_delete=models.PROTECT)
	created_by = models.CharField(max_length=25, blank=True)
	updated_by = models.CharField(max_length=25, blank=True)
	created_time = models.CharField(max_length=50, blank=True)
	updated_time = models.CharField(max_length=50, blank=True)
	active_status = models.BooleanField(default=True)
	def __str__(self):
		return "[participant_id : " + unicode(self.participant_id)+ ", name : "+unicode(self.name)+ ", active_status : "+unicode(self.active_status)+"]"

class Child(models.Model):
	child_id = models.CharField(max_length=12, blank=True)
	name = models.CharField(max_length=30, blank=True)
	mother = models.ForeignKey(Participant, on_delete=models.PROTECT)	
	def __str__(self):
		return "[mother name : " + unicode(self.mother.name)+ ", child name : "+unicode(self.name)+"]"

core/forms.py
from django.forms import *
from .models import * 
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.forms import AuthenticationForm 
from django.contrib.auth.models import User
import datetime

class LoginForm(AuthenticationForm):
    username = CharField(label="Username", max_length=30, 
                               widget=TextInput(attrs={'class': 'form-control', 'name': 'username', 'placeholder':'Username...'}))
    password = CharField(label="Password", max_length=30, 
                               widget=PasswordInput(attrs={'class': 'form-control', 'name': 'password', 'placeholder':'Password...'}))
    def __init__(self, *args, **kwargs):
        super(LoginForm,self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['autofocus'] = 'on'
        self.error_messages['invalid_login'] = "Your username and password didn't match. Please try again."

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email','first_name','last_name', 'password')     
        widgets = {'username' : TextInput(attrs={'autofocus' : '','class' : 'form-control form-username', 'id' :'form-username', 'placeholder' : 'Username...'}), 'email' : EmailInput(attrs={'class' : 'form-control'}), 'first_name' : TextInput(attrs={'class' : 'form-control'}), 'last_name' : TextInput(attrs={'class' : 'form-control'}),
                     'password' : PasswordInput(attrs={'class' : 'form-control form-password', 'id' :'form-password', 'placeholder' : 'Password...'})}
        help_texts = {
            'username': None,
        }
    def clean(self):
        username = self.cleaned_data.get("username")
        user = User.objects.get(username=username)
        password =  self.cleaned_data.get("password")
        if not user.check_password(password):
            msg = "Current Password wrong"
            self._errors["password"] = self.error_class([msg])
    def __init__(self, *args, **kwargs):
        super(UserForm,self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['readonly'] = True               

core/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth import update_session_auth_hash
from .models import *
import datetime

## FORMS Fadli
from forms_a.models import *
from forms_d.models import *
##

## FORMS GAMA
from forms_b1.models import *
from forms_b2.models import *
from forms_b3.models import *
from forms_c.models import *
##

@login_required(login_url='core:login')
def home(request):
	return redirect('/participant')

@login_required(login_url='core:login')
def summary(request):
	if request.user.is_staff or True: ##kalau mau data entry biasa tidak bisa akses maka hapus or True nya
		#participants = Participant.objects.filter(active_status=True)
		participants = Participant.objects.all()
		summary_list = []
		number_of_completed_participant = 0

		###### filling summary_list ######
		for participant in participants:
			### form A ####
			try:
				form_a = ABaseLine.objects.get(participant=participant)
				if form_a.data_checked_id != None and form_a.data_checked_id != "":
					form_a_status = "3"
				elif form_a.is_save_all:
					form_a_status = "2"
				else:
					form_a_status = "1"
			except:
				form_a_status = ""
			####

			### form B1 ####
			try:
				form_b1 = B1Pregnancy.objects.get(participant=participant)
				if form_b1.data_checked_id != None and form_b1.data_checked_id != "":
					form_b1_status = "3"
				elif form_b1.is_save_all:
					form_b1_status = "2"
				else:
					form_b1_status = "1"	
			except:
				form_b1_status = ""
			####

			### form B2 ####
			try:
				form_b2 = B2Pregnancy.objects.get(participant=participant)
				if form_b2.data_checked_id != None and form_b2.data_checked_id != "":
					form_b2_status = "3"
				elif form_b2.is_save_all:
					form_b2_status = "2"
				else:
					form_b2_status = "1"	
			except:
				form_b2_status = ""
			####

			### form B3 ####
			try:
				form_b3 = B3Pregnancy.objects.get(participant=participant)
				if form_b3.data_checked_id != None and form_b3.data_checked_id != "":
					form_b3_status = "3"
				elif form_b3.is_save_all:
					form_b3_status = "2"
				else:
					form_b3_status = "1"	
			except:
				form_b3_status = ""
			####

			### form C ####
			form_c_all_complete = True
			try:
				form_c_list = CBirth.objects.filter(participant=participant)
				form_c_status = ""
				for form_c in form_c_list:
					if form_c.data_checked_id != None and form_c.data_checked_id != "":
						form_c_status = form_c_status + form_c.child_name + " - 3 | "
					elif form_c.is_save_all:
						form_c_status = form_c_status + form_c.child_name + " - 2 | "
						form_c_all_complete = False
					else:
						form_c_status = form_c_status + form_c.child_name + " - 1 | "
						form_c_all_complete = False	
				form_c_status = form_c_status[:-3]
			except:
				form_c_status = ""
				form_c_all_complete = False
			####

			### form D1 ####
			form_d1_all_complete = True
			try:
				form_d1_list = DInfant.objects.filter(participant=participant)
				form_d1_status = ""
				for form_d1 in form_d1_list:
					if form_d1.data_checked_id != None and form_d1.data_checked_id != "":
						form_d1_status = form_d1_status + form_d1.child_name + " - 3 | "
					elif form_d1.is_save_all:
						form_d1_status = form_d1_status + form_d1.child_name + " - 2 | "
						form_d1_all_complete = False
					else:
						form_d1_status = form_d1_status + form_d1.child_name + " - 1 | "
						form_d1_all_complete = False
				form_d1_status = form_d1_status[:-3]
			except:
				form_d1_status = ""
				form_d1_all_complete = False
			####

			### form D2 ####
			form_d2_all_complete = True
			try:
				form_d2_list = DInfant2.objects.filter(participant=participant)
				form_d2_status = ""
				for form_d2 in form_d2_list:
					if form_d2.data_checked_id != None and form_d2.data_checked_id != "":
						form_d2_status = form_d2_status + form_d2.child_name + " - 3 | "
					elif form_d2.is_save_all:
						form_d2_status = form_d2_status + form_d2.child_name + " - 2 | "
						form_d2_all_complete = False
					else:
						form_d2_status = form_d2_status + form_d2.child_name + " - 1 | "
						form_d2_all_complete = False	
				form_d2_status = form_d2_status[:-3]
			except:
				form_d2_status = ""
				form_d2_all_complete = False
			####

			### form D3 ####
			form_d3_all_complete = True
			try:
				form_d3_list = DInfant3.objects.filter(participant=participant)
				form_d3_status = ""
				for form_d3 in form_d3_list:
					if form_d3.data_checked_id != None and form_d3.data_checked_id != "":
						form_d3_status = form_d3_status + form_d3.child_name + " - 3 | "
					elif form_d3.is_save_all:
						form_d3_status = form_d3_status + form_d3.child_name + " - 2 | "
						form_d3_all_complete = False
					else:
						form_d3_status = form_d3_status + form_d3.child_name + " - 1 | "
						form_d3_all_complete = False
				form_d3_status = form_d3_status[:-3]
			except:
				form_d3_status = ""
				form_d3_all_complete = False
			####

			### form D4 ####
			form_d4_all_complete = True
			try:
				form_d4_list = DInfant4.objects.filter(participant=participant)
				form_d4_status = ""
				for form_d4 in form_d4_list:
					if form_d4.data_checked_id != None and form_d4.data_checked_id != "":
						form_d4_status = form_d4_status + form_d4.child_name + " - 3 | "
					elif form_d4.is_save_all:
						form_d4_status = form_d4_status + form_d4.child_name + " - 2 | "
						form_d4_all_complete = False
					else:
						form_d4_status = form_d4_status + form_d4.child_name + " - 1 | "
						form_d4_all_complete = False	
				form_d4_status = form_d4_status[:-3]
			except:
				form_d4_status = ""
				form_d4_all_complete = False
			####

			if form_a_status == "3" and form_b1_status == "3" and form_b2_status == "3" and form_c_all_complete and form_d1_all_complete and form_d2_all_complete and form_d3_all_complete and form_d4_all_complete:
				number_of_completed_participant = number_of_completed_participant + 1

			summary_list.append([participant.participant_id, participant.name, form_a_status, form_b1_status, form_b2_status, form_b3_status, form_c_status, form_d1_status, form_d2_status, form_d3_status, form_d4_status, participant.id, participant.active_status])	
		
		###### end of filling summary_list ######

		return render(request, 'core/summary.html', {'summary_list' : summary_list, 'number_of_completed_participant' : number_of_completed_participant})
	
	else:
		return home(request)


@login_required(login_url='core:login')
def create_participant(request):
	puskesmas_id = request.POST.get('puskesmas')
	number_of_people = Participant.objects.filter(puskesmas_id=puskesmas_id).count()
	puskesmas_obj = Puskesmas.objects.get(id=puskesmas_id)
	participant_obj = Participant()
	participant_obj.name = request.POST.get('participant_name')
	participant_obj.date_admission = request.POST.get('date_admission')
	participant_obj.participant_id =  puskesmas_obj.puskesmas_id+format_number(number_of_people+1)
	participant_obj.puskesmas_id = puskesmas_id
	participant_obj.created_by = request.user.username
	participant_obj.updated_by = request.user.username
	participant_obj.created_time = datetime.now()
	participant_obj.updated_time = datetime.now()
	participant_obj.save()
	return home(request)

### UNUSED SINCE EDIT PARTICIPANT IS NOT IMPLEMENTED 
@login_required(login_url='core:login')
def edit_participant(request, participant_id):
	participant_obj = Participant.objects.get(id=participant_id)
	participant_obj.name = request.POST.get('participant_name_edit')
	participant_obj.date_admission = request.POST.get('participant_date_edit')
	participant_obj.edited_by = request.user.username
	participant_obj.edited_time = datetime.now()
	participant_obj.save()
	return home(request)
###


def format_number(number):
	if number < 10:
		return "00" + str(number)
	elif number < 100:
		return "0" + str(number)
	else:
		return str(number)			

@login_required(login_url='core:login')
def redirect_to_forms(request, participant_id):
	return redirect('/participant/'+str(participant_id)+'/')	

@login_required(login_url='core:login')
def participant_list(request):
	participants = Participant.objects.filter(active_status=True)
	puskesmas_list = Puskesmas.objects.all()
	number_of_participants_list = []
	for puskesmas in puskesmas_list:
		number_of_participants_list.append(puskesmas.name + ": " + str(Participant.objects.filter(puskesmas=puskesmas).count()))	
	return render(request, 'core/home.html', {'number_of_participants_list' : number_of_participants_list,'participants' : participants, 'puskesmas_list' : puskesmas_list})


@login_required(login_url='core:login')
def forms(request, participant_id):
	participant = Participant.objects.get(id=participant_id)
	date_admission = participant.date_admission.__str__()
	return render(request, 'core/forms.html', {'participant' : participant, 'date_admission' : date_admission})

##################################
# form fadli
@login_required(login_url='core:login')
def form_a(request, participant_id):
	participant = Participant.objects.get(id=participant_id)
	forms = ABaseLine.objects.filter(participant_id=participant_id)
	date_admission = participant.date_admission.__str__()
	return render(request, 'core/form_a.html', {'participant' : participant, 'forms' : forms, 'date_admission' : date_admission})

@login_required(login_url='core:login')
def form_d(request, participant_id, visiting_id):
	participant = Participant.objects.get(id=participant_id)
	child_list = Child.objects.filter(mother=participant)
	forms = None
	visiting_number = ""
	if visiting_id == "1":
		forms = DInfant.objects.filter(participant_id=participant_id)
		visiting_number = "First"
	elif visiting_id == "2":
		forms = DInfant2.objects.filter(participant_id=participant_id)
		visiting_number = "Second"
	elif visiting_id == "3":
		forms = DInfant3.objects.filter(participant_id=participant_id)
		visiting_number = "Third"

core/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="PEER Data Management Application">
    <meta name="author" content="Muhammad Fadli Putra dan Vasko Dagama">

    <title>PEER</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/select/1.2.2/css/select.dataTables.min.css">
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script> 
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.1.1/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.1.1/js/responsive.bootstrap.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/select/1.2.2/js/dataTables.select.min.js"></script>
    
    
    <!-- jquery-confirm -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.js"></script>

    <!-- Custom CSS -->
    <style>

        html {
          height: 100%;
        }
        body {
          min-height: 100%;
          padding-top: 70px;
          position: relative;
          margin: 0;
          padding-bottom: 6rem;
        }

        .list-group .active a {
            color: white;
        }

        .mycenter {
            margin: auto;
            width: 100%;
        }

        #myTable {
            margin: auto;
        }

        #myTable th{
            background-color: #4CAF50;
            color: white;
        }

        #myTable td a {
            width:100%;
        }

        #myTable tr:hover {
              background-color: #ffff99;
              cursor: pointer; 
        }

        .footer {
          position: absolute;
          right: 0;
          bottom: 0;
          left: 0;
          padding: 1rem;
          background-color: #222;
          border-color: #080808;
          text-align: center;
        }

    .navbar.navbar-inverse{
            background-color:#577da5;
            border-color: white;
        }

        #myTable th{
            background-color: #2da55d;
        }

    .actives a{
        color:red;
    }

    </style>    

    {% if is_save_all %}
        <script>
         $(document).ready(function(){
               $("#form_a :input").prop("disabled", true);
               $("#form_d :input").prop("disabled", true);

               $("#form_c :input").prop("disabled", true);
               $("#form_b1 :input").prop("disabled", true);
               $("#form_b2 :input").prop("disabled", true);
               $("#form_b3 :input").prop("disabled", true);
               
               $("#submit_button").prop("disabled", false);
            });
        </script>
    {% endif %}

    <script>
        $(document).ready(function($) {
                $(".clickable-row").click(function() {
                    window.location = $(this).data("href");
                });
        });    
    </script>
        
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'core:home' %}" style="color:white; font-family:verdana;">PEER Data Management</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                    <a href="../" style="color:white; font-family:verdana;">Back</a>
                    </li>
                    <li>
                        <a href="{% url 'core:home' %}" style="color:white; font-family:verdana;">Home</a>
                    </li>
                    <!-- {% if request.user.is_staff %}
                    <li>
                        <a href="{% url 'core:summary' %}" style="color:white; font-family:verdana;">Summary</a>
                    </li>
                    {% endif %} -->
                    <li>
                        <a href="{% url 'core:summary' %}" style="color:white; font-family:verdana;">Summary</a>
                    </li>
                    <li>
                        <a href="#" style="color:white; font-family:verdana;">You're login as {{ request.user.username }}</a>
                    </li>
                    <li>
                        <a href="{% url 'core:logout'%}" style="color:red; font-family:verdana;">Logout</a>
                    </li>
                </ul>
            </div>  
            <!-- /.navbar-collapse -->
            
        </div>
        <!-- /.container -->
    </nav>
    

    {% block content %}

    {% endblock %}
    
    <script type="text/JavaScript">
        $(document).ready(function(){
            //$('#myTable').DataTable();
            $('#myTable').DataTable( {
                select: true
            } );
            
        });

    </script>

    <div class="footer">
      <div class="container">
        <p class="text-muted" style="color:white; font-family:verdana;">PEER Data Management &copy; 2017</p>
      </div>
    </div>
    
</body>
</html>

core/templates/brief-header.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
        <div class="jumbotron participantBox">         
            <form class="patient-form-data">
                <div class="row">
                    <div class="col-md-6 col-md-offset-3 col-xs-6 col-xs-offset-3 col-sm-6 col-sm-offset-3">
                        <div class="form-group">
                            <label for="participant_id"> Participant ID</label>
                            <input class="form-control disabled" type="text" value="{{participant.participant_id}}" readonly>
                        </div>

                        <div class="form-group">
                            <label for="participant_name"> Participant Name </label>
                            <input class="form-control" type="text" value="{{participant.name}}" readonly>
                        </div>

                        <div class="form-group">
                            <label for="participant_name"> Puskesmas </label>
                            <input class="form-control" type="text" value="{{participant.puskesmas.name}}" readonly>
                        </div>

                        <div class="form-group">
                            <label for="date_admission"> Date Admission </label>
                            <input class="form-control" type="date" value="{{date_admission}}" readonly>
                        </div>                        
                    </div>                     
                </div> 
            </form>
        </div>

        {% block content2 %}
        {% endblock %}
</div>

{% endblock %}        